### ISSUE TITLE
[Error] Failed to recover from the collection snapshot.

### ISSUE THREAD

**Issue by airlover99** [GaiaNet-AI/gaianet-node#64] opened 2024-06-06 17:25 UTC
![image](https://github.com/GaiaNet-AI/gaianet-node/assets/76697564/487a7217-5559-46b7-81d5-1eb29889a69b)

Describe the bug
I encountered an error while initializing GaiaNet. The process fails with a "Service internal error: Tokio task join error."

To Reproduce

Run gaianet init
Wait for the process to download necessary files and create a collection in the Qdrant instance.
The error occurs during the import of the Qdrant collection snapshot.

**Comment by juntao** [comment] 2024-06-06 19:51
Also, if you are using this under WSL, checkout this solution:

https://docs.gaianet.ai/node-guide/troubleshooting#fail-to-recover-from-collection-snapshot-on-windows-wsl

**Comment by airlover99** [comment] 2024-06-07 00:38
> Also, if you are using this under WSL, checkout this solution:
> 
> https://docs.gaianet.ai/node-guide/troubleshooting#fail-to-recover-from-collection-snapshot-on-windows-wsl

Yes，I am using WSL.The method of this link is useful, thank you for your help

**Comment by alabulei1** [comment] 2024-06-10 02:19
I'm going to close this issue, since the problem is solved.

**Closed by alabulei1** 2024-06-10 02:19 UTC
